// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltoeeluuavfruvybiwfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0b2VlbHV1YXZmcnV2eWJpd2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjE3MDAsImV4cCI6MjA2MDA5NzcwMH0.WMwfKC8PTfi513HsJScveVC417Ajb9raLC2ZW2raajk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);